### ISSUE TITLE
[Bug] - Consistently being asked for a password for MusicianComm

### ISSUE THREAD

**Issue by NayteDogg** [LenweSaralonde/Musician#86]
### Description

In the Wotlk Classic, players are getting frequently spammed with a dialog box that says to enter a password for MusicianComm. No matter what they do, enter a password or not, they continue to get spammed with this dialog box.

### Reproduction steps

1. Log in to Wotlk classic servers with addon
2. Just wait around
3.

### Actual behavior

A password Dialog box appears and is spammy

### Expected behavior

Dont think players should be needing to enter a password for anything.

### Screenshots

![Screenshot 2022-09-06 225728](https://user-images.githubusercontent.com/51131767/188792180-b6846b7b-0536-4814-beaa-8975d4796f5a.png)

### World of Warcraft flavor

Wrath of the Lich King Classic

### World of Warcraft version

3.4.0 (45435)

### Add-on version

1.9.1.1

### Have you tried disabling all your other add-ons to ensure only this add-on causes the issue?

Yes

**Comment by LenweSaralonde** [comment]
Typo in onChannelFailed() function in Musician.Comm , WRONG_PASSWORD is nil and should be within a string.

In case of incorrect password:
* Retry to join with no password (it may have been removed accidentally by the current channel owner)
* Increase retry delay to 10 minutes when passworded on Retail
* Give up on Classic since the Comm channel is not mandatory on Classic.
* Attempt to hide the password popup if the joining process was not initiated manually.
